services:
  - postgresql

before_script:
  - psql -U postgres -c 'CREATE DATABASE chitter_test;'
  - psql -d chitter_test -U postgres -f db/migrations/01_databases_creation.sql

script:
  - bundle exec rspec
